# Generated by Django 5.1.5 on 2025-01-25 17:17

import b_hostels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_hostels', '0003_alter_hostel_hostel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintimage',
            name='images',
            field=models.ImageField(upload_to=b_hostels.models.user_directory_path),
        ),
    ]
