# Generated by Django 5.1.5 on 2025-01-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_hostels', '0004_alter_complaintimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
