# Generated by Django 5.1.5 on 2025-01-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauthapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_female_potter',
            new_name='is_female_potter_amazon',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_male_potter',
            new_name='is_female_potter_serena',
        ),
        migrations.AddField(
            model_name='user',
            name='is_male_potter_new_boys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_male_potter_old_boys',
            field=models.BooleanField(default=False),
        ),
    ]
